LeavittSoftware/titanium-elements

packages/profile-picture/src/profile-picture-menu.ts
packages/storybook/stories/profile-picture.stories.js
packages/titanium-toolbar/src/titanium-toolbar.ts

- titanium-toolbar padding
- profile picture menu story
- button order on profile picture menu

Fixes a few things

---

packages/storybook/stories/data-table.stories.js
packages/titanium-data-table/src/titanium-data-table-item.ts

Sometimes isClicking is not allowing items to be selected or navigated to.

fix: double click not always firing on data-table-item.

---

packages/storybook/stories/data-table.stories.js
packages/titanium-data-table/src/titanium-data-table.ts

Aligns tables actions to line up with search on the right edge.

fix: align search and tables actions

---

packages/titanium-error-page/src/titanium-error-page.ts

fix: style needs to apply to img tag not svg tag

---

packages/titanium-address-input/src/google-address-input.ts
packages/titanium-address-input/src/titanium-address-input.ts

I can't get storybook to build locally for me, but this should be correct.

Fix: Adds helper to address input

---

packages/titanium-address-input/src/google-address-input.ts

Aaron asked we remove this check. Its preventing you form setting another address after one has been set.

Address input select address bug

---

packages/storybook/package.json
packages/storybook/stories/titanium-youtube-input.stories.mdx
packages/titanium-youtube-input/.gitignore
packages/titanium-youtube-input/CHANGELOG.md
packages/titanium-youtube-input/package.json
packages/titanium-youtube-input/src/titanium-youtube-input.ts
packages/titanium-youtube-input/tsconfig.json
tsconfig.json

154 Add youtube input

---

packages/leavitt-elements/src/mwc-datefield.ts
packages/storybook/stories/titanium-data-table.stories.mdx
packages/titanium-chip/src/titanium-chip.ts
packages/titanium-data-table/package.json
packages/titanium-data-table/src/titanium-data-table-header.ts
packages/titanium-data-table/src/titanium-data-table-item.ts
packages/titanium-data-table/src/titanium-data-table.ts

Data Table vNext

---

packages/storybook/demos/data-table-paging-demo.ts
packages/storybook/stories/titanium-data-table.stories.mdx
packages/storybook/stories/titanium-page-control.stories.mdx
packages/titanium-data-table/src/titanium-data-table.ts
packages/titanium-data-table/src/titanium-page-control.ts

BREAKING CHANGE: updates how the data table take and page works. Simplifies the usage. Finishes the page-control component.

feat: Adds page control element

---

packages/leavitt-file-explorer/src/leavitt-file-explorer.ts
packages/storybook/stories/leavitt-file-explorer.stories.mdx

192 Hide the sub header file count/size when prevent navigation is set

---

.github/workflows/pr-auto-assign.yml
.github/workflows/storybook.yml

fix: updates build script to use node 14

---

packages/leavitt-elements/src/leavitt-date-range.ts
packages/leavitt-elements/src/mwc-datefield.ts
packages/storybook/stories/date-field.stories.mdx
packages/storybook/stories/leavitt-date-range.stories.mdx

Also fixes DateField issue causing label to overlay placeholder when layout() is called on an empty DateField and exposes layout() on leavitt-date-range.

Add all-time option to date range

---

packages/user-manager/src/user-manager.ts

Needed so lookupunitedvalley can authenticate against loginapi.unitedvalley.com tokens

feat(user-manager): make issuer identifier a property

---

packages/storybook/package.json
packages/storybook/stories/titanium-input-validator.stories.mdx
packages/titanium-input-validator/.gitignore
packages/titanium-input-validator/package.json
packages/titanium-input-validator/src/titanium-input-validator.ts
packages/titanium-input-validator/tsconfig.json
tsconfig.json

219 Add form-validator

---

packages/storybook/.storybook/manager.js
packages/storybook/.storybook/preview.js
packages/storybook/package.json
packages/storybook/stories/titanium-chip-multi-select.stories.mdx
packages/titanium-chip-multi-select/.gitignore
packages/titanium-chip-multi-select/package.json
packages/titanium-chip-multi-select/src/titanium-chip-multi-select.ts
packages/titanium-chip-multi-select/tsconfig.json
tsconfig.json

216 Add titanium-chip-multi-select

---

packages/leavitt-elements/src/leavitt-company-select.ts
packages/titanium-address-input/src/manual-address-dialog.ts
packages/titanium-address-input/src/manual-address-form.ts

Needed to fix using components within a dialog

Adds layout() to company select and manual address form

---

packages/leavittbook/src/components/titanium-access-denied-page.ts
packages/leavittbook/src/my-app.ts

feat(leavittbook): creates titanium-access-denied-page demo

---

packages/leavittbook/src/components/leavitt-person-select.ts
packages/leavittbook/src/my-app.ts

245 Create a leavitt-person-select demo

---

packages/leavittbook/src/components/titanium-progress.ts
packages/leavittbook/src/my-app.ts

feat(leavittbook): creates titanium-progress demo

---

packages/leavittbook/src/components/profile-picture-demo.ts
packages/leavittbook/src/my-app.ts

Closes #266
I didn't include size 512 in the examples due to it being HUGE

266 Create a profile-picture demo

---

packages/leavittbook/src/components/titanium-error-page.ts
packages/leavittbook/src/my-app.ts

feat(leavittbook): creates titanium-error-page demo

---

packages/leavittbook/src/components/titanium-card-list-item-demo.ts
packages/leavittbook/src/my-app.ts

281 Create a titanium-card-list-item demo

---

packages/leavittbook/src/components/titanium-side-menu-item-demo.ts
packages/leavittbook/src/my-app.ts

271 Create a titanium-side-menu demo

---

packages/leavittbook/src/components/profile-picture-demo.ts
packages/leavittbook/src/components/titanium-header.ts
packages/leavittbook/src/my-app.ts

feat(leavittbook): creates titanium-header demo

---

packages/leavittbook/src/components/titanium-tab-control-demo.ts
packages/leavittbook/src/my-app.ts

289 Create a titanium-tab-control demo

---

packages/leavittbook/src/components/titanium-search-input-demo.ts
packages/leavittbook/src/my-app.ts

268 Create a titanium-search-input demo

---

packages/leavittbook/src/components/titanium-toolbar-demo.ts
packages/leavittbook/src/my-app.ts

278 Create a titanium-toolbar demo

---

packages/leavittbook/package.json
packages/leavittbook/src/components/mwc-datefield-demo.ts
packages/leavittbook/src/my-app.ts

239 Create an mwc-datefield demo

---

package.json
packages/leavitt-elements/src/leavitt-person-select.ts
packages/leavitt-file-explorer/src/leavitt-file-explorer.ts
packages/leavittbook/.gitignore
packages/leavittbook/index.html
packages/leavittbook/package.json
packages/leavittbook/src/components/leavitt-file-explorer.ts
packages/leavittbook/src/components/leavitt-person-select.ts
packages/leavittbook/src/components/mwc-datefield-demo.ts
packages/leavittbook/src/components/profile-picture-demo.ts
packages/leavittbook/src/components/titanium-access-denied-page.ts
packages/leavittbook/src/components/titanium-button.ts
packages/leavittbook/src/components/titanium-card-list-item-demo.ts
packages/leavittbook/src/components/titanium-error-page.ts
packages/leavittbook/src/components/titanium-header.ts
packages/leavittbook/src/components/titanium-progress.ts
packages/leavittbook/src/components/titanium-search-input-demo.ts
packages/leavittbook/src/components/titanium-side-menu-item-demo.ts
packages/leavittbook/src/components/titanium-tab-control-demo.ts
packages/leavittbook/src/components/titanium-toolbar-demo.ts
packages/leavittbook/src/components/titanium-twoline-formfield.ts
packages/leavittbook/src/styles/story-styles.ts
packages/titanium-helpers/src/titanium-load-while.ts

236 Research a way to show api docs from the custom-components .json file

---

.github/workflows/build-lint-publish.yml
.gitignore
package.json
packages/leavittbook/rollup.config.js

chore(leavittbook): set up build for components.leavitt.com

---

packages/leavittbook/package.json
packages/leavittbook/src/components/titanium-input-validator-demo.ts
packages/leavittbook/src/my-app.ts
packages/titanium-input-validator/src/titanium-input-validator.ts

262 Create a titanium-input-validator demo

---

packages/leavittbook/src/components/titanium-data-table-item-demo.ts
packages/leavittbook/src/my-app.ts
packages/titanium-data-table/src/titanium-data-table-item.ts

253 Create a titanium-data-table-item demo

---

packages/leavittbook/src/demos/titanium-loading-indicator/index.html
packages/leavittbook/src/demos/titanium-loading-indicator/project.json
packages/leavittbook/src/demos/titanium-loading-indicator/titanium-loading-indicator-demo.ts
packages/leavittbook/src/demos/titanium-loading-indicator/titanium-loading-indicator-playground.ts
packages/leavittbook/src/my-app.ts
packages/titanium-loading-indicator/src/titanium-loading-indicator.ts

feat(leavittbook): creates a titanium-loading-indicator demo

---

packages/leavittbook/src/demos/titanium-styles/index.html
packages/leavittbook/src/demos/titanium-styles/project.json
packages/leavittbook/src/demos/titanium-styles/titanium-styles-demo.ts
packages/leavittbook/src/demos/titanium-styles/titanium-styles-playground.ts
packages/leavittbook/src/my-app.ts

feat(leavittbook): add titanium-styles demo

---

packages/leavittbook/src/demos/titanium-icon/index.html
packages/leavittbook/src/demos/titanium-icon/project.json
packages/leavittbook/src/demos/titanium-icon/titanium-icon-demo.ts
packages/leavittbook/src/demos/titanium-icon/titanium-icon-playground.ts
packages/leavittbook/src/my-app.ts

260 Create a titanium-icon demo

---

packages/leavittbook/src/demos/titanium-single-select/index.html
packages/leavittbook/src/demos/titanium-single-select/project.json
packages/leavittbook/src/demos/titanium-single-select/titanium-single-select-demo.ts
packages/leavittbook/src/demos/titanium-single-select/titanium-single-select-playground.ts
packages/leavittbook/src/my-app.ts

272 Create a titanium-single-select

---

packages/leavittbook/src/demos/titanium-select/index.html
packages/leavittbook/src/demos/titanium-select/project.json
packages/leavittbook/src/demos/titanium-select/titanium-select-demo.ts
packages/leavittbook/src/demos/titanium-select/titanium-select-playground.ts
packages/leavittbook/src/my-app.ts

269 Create a titanium-select demo

---

packages/leavittbook/src/demos/titanium-svg-button-menu/index.html
packages/leavittbook/src/demos/titanium-svg-button-menu/project.json
packages/leavittbook/src/demos/titanium-svg-button-menu/titanium-svg-button-menu-demo.ts
packages/leavittbook/src/demos/titanium-svg-button-menu/titanium-svg-button-menu-playground.ts
packages/leavittbook/src/my-app.ts
packages/titanium-svg-button/src/titanium-svg-button-menu.ts

feat(leavittbook): creates a titanium-svg-button-menu demo

---

packages/leavittbook/src/demos/titanium-single-action-card/index.html
packages/leavittbook/src/demos/titanium-single-action-card/project.json
packages/leavittbook/src/demos/titanium-single-action-card/titanium-single-action-card-demo.ts
packages/leavittbook/src/demos/titanium-single-action-card/titanium-single-action-card-playground.ts
packages/leavittbook/src/my-app.ts
packages/titanium-card/src/titanium-single-action-card.ts

284 Create a titanium-single-action-card demo

---

packages/leavittbook/src/demos/profile-picture-menu/index.html
packages/leavittbook/src/demos/profile-picture-menu/profile-picture-menu-demo.ts
packages/leavittbook/src/demos/profile-picture-menu/profile-picture-menu-playground.ts
packages/leavittbook/src/demos/profile-picture-menu/project.json
packages/leavittbook/src/my-app.ts
packages/profile-picture/src/profile-picture-menu.ts

265 Create a profile-picture-menu demo

---

packages/leavittbook/src/demos/titanium-toggle-button/index.html
packages/leavittbook/src/demos/titanium-toggle-button/project.json
packages/leavittbook/src/demos/titanium-toggle-button/titanium-toggle-button-demo.ts
packages/leavittbook/src/demos/titanium-toggle-button/titanium-toggle-button-playground.ts
packages/leavittbook/src/my-app.ts
packages/titanium-button/src/titanium-toggle-button.ts

feat(leavittbook): creates a titanium toggle button demo

---

packages/leavittbook/package.json
packages/leavittbook/src/demos/leavitt-person-group-select/leavitt-person-group-select-playground.ts
packages/leavittbook/src/demos/titanium-youtube-input/index.html
packages/leavittbook/src/demos/titanium-youtube-input/project.json
packages/leavittbook/src/demos/titanium-youtube-input/titanium-youtube-input-demo.ts
packages/leavittbook/src/demos/titanium-youtube-input/titanium-youtube-input-playground.ts
packages/leavittbook/src/my-app.ts
packages/titanium-youtube-input/src/titanium-youtube-input.ts

280 Create a titanium-youtube-input

---

packages/leavittbook/src/demos/titanium-search-input/titanium-search-input-playground.ts
packages/titanium-search-input/src/titanium-search-input.ts

310 titanium-search-input focus() method doesn't work if collapsed

---

package.json
packages/leavittbook/src/demos/titanium-snackbar/titanium-snackbar-playground.ts
packages/titanium-snackbar/src/titanium-snackbar.ts

feat: increase font, adds more stories for snackbar, updates lerna

---

packages/titanium-image-input/src/image-cropper-dialog.ts

fix(titanium-image-input): add focus trap

---

packages/leavittbook/package.json
packages/leavittbook/src/demos/titanium-color-input/index.html
packages/leavittbook/src/demos/titanium-color-input/project.json
packages/leavittbook/src/demos/titanium-color-input/titanium-color-input-demo.ts
packages/leavittbook/src/demos/titanium-color-input/titanium-color-input-playground.ts
packages/leavittbook/src/my-app.ts
packages/titanium-color-input/.gitignore
packages/titanium-color-input/package.json
packages/titanium-color-input/src/titanium-color-input.ts
packages/titanium-color-input/tsconfig.json
tsconfig.json

404 Create a titanium-color-input or similar (take it from manage.leavittlink.com)

---

README.md

Adds docs for making new components

docs(leavittbook): updates readme

---

packages/leavittbook/src/demos/titanium-dialog/titanium-dialog-playground.ts
packages/titanium-dialog/src/titanium-native-dialog-base.ts

This is an unfortunate behavior of the native dialog

fix(titanium-dialog): stop events from leaving the dialog

---

packages/leavittbook/src/demos/titanium-data-table/draggable.ts
packages/titanium-data-table/src/titanium-data-table-item.ts

Fix href's not working on items on touch devices

fix(titanium-data-table):  allow touch events on draggable items on mobile

---

packages/leavittbook/src/demos/titanium-address-input/titanium-address-input-playground.ts
packages/titanium-address-input/src/titanium-address-input.ts

428 titanium-address-input should allow setting the "Can't find my address" text

---

packages/titanium-address-input/src/google-address-input.ts
packages/titanium-dialog/src/titanium-native-dialog-base.ts

Misc bug fixes / feature requests

---

packages/leavitt-file-explorer/src/leavitt-add-folder-modal.ts
packages/leavitt-file-explorer/src/leavitt-file-explorer.ts

462 Getting a different Error screen for Permission denied on file explorer

---

packages/leavittbook/src/demos/titanium-date-range-selector/titanium-date-range-selector-playground.ts
packages/titanium-date-range-selector/src/titanium-date-range-selector.ts

possibly closes #463
Dear Aaron,
I didn't want to put too much time into this if I am heading in the wrong direction. So I wanted to PR early to get an idea for what you are thinking.
Thanks,
Kasey

463 Add time functionality to titanium-date-range-selector

---

packages/leavitt-file-explorer/src/leavitt-folder-modal.ts

Fixes https://github.com/LeavittSoftware/enterprisemanager.leavitt.com/issues/104

fix(leavitt-file-explorer): fix undefined apiService

---

packages/leavittbook/src/demos/titanium-data-table/full-working-example.ts
packages/titanium-data-table/src/titanium-page-control.ts

For when there are options with more than 2 digits

feat(titanium-data-table): adds css variable to set width of select in page-control

---

packages/leavittbook/src/getting-started.ts
packages/leavittbook/src/my-app.ts
packages/leavittbook/src/shared/npm-stats.ts
packages/leavittbook/src/styles/form-styles.ts
packages/leavittbook/src/styles/my-app-styles.ts
packages/leavittbook/src/styles/story-styles.ts
packages/web/package.json
packages/web/titanium/data-table/data-table-item.ts
packages/web/titanium/data-table/data-table.ts
packages/web/titanium/date-range-selector/date-range-selector.ts
packages/web/titanium/duration-input/duration-input.ts
packages/web/titanium/single-select-base/single-select-base.ts
packages/web/titanium/snackbar/snackbar.ts

fixes: #523
fixes: #520
fixes: #525
fixes: #522
fixes: #530

Clean up issues

---

packages/leavittbook/src/demos/titanium-data-table-header/titanium-data-table-header-playground.ts
packages/web/titanium/address-input/manual-address-dialog.ts
packages/web/titanium/hacks/report-validity-if-error.ts

closes #521
fixes manual address dialog using a file it doesn't have access to

kasey bugs

---

packages/leavittbook/src/demos/titanium-drawer/titanium-drawer-playground.ts
packages/leavittbook/src/demos/titanium-icon-picker/titanium-icon-picker-playground.ts

Closes #527
Closes #528
Closes #529

Fix titanium-drawer demo, fix icon-picker demo

---

packages/leavittbook/src/demos/titanium-input-validator/titanium-input-validator-playground.ts

Removed textfield and made more consistent with other input demos
Closes #531

fix: update titanium-input-validator demo

---

packages/web/titanium/data-table/data-table-item.ts

feat(titanium-data-table-item): add :hover background-color support for Firefox

---

packages/web/leavitt/api-service/api-service.ts
packages/web/leavitt/person-company-select/person-company-select.ts
packages/web/leavitt/person-group-select/person-group-select.ts
packages/web/titanium/chip-multi-select/chip-multi-select.ts

closes #526
I didn't put all the properties because it seems like Aaron only wants the ones we will most likely ever use.

526 Titanium chip multi select not passing through all the properties that field supports in titanium validator. Specifically error text

---

packages/leavittbook/src/demos/titanium-page-control/titanium-page-control-playground.ts
packages/web/leavitt/api-service/api-service.ts
packages/web/leavitt/person-company-select/person-company-select.ts
packages/web/leavitt/person-group-select/person-group-select.ts

closes #532
Might need to clear your localstorage props 1 time but should work from there

532 titanium-page-control demo localstorage take key needs to be defined

---

packages/web/leavitt/company-select/company-select.ts
packages/web/leavitt/person-group-select/person-group-select.ts

533 leavitt-person-group-select and leavitt-person-company-select components need to update their fuse tops to restrict the number of results

---

packages/leavittbook/src/demos/titanium-date-input/index.html
packages/leavittbook/src/demos/titanium-date-input/project.json
packages/leavittbook/src/demos/titanium-date-input/titanium-date-input-demo.ts
packages/leavittbook/src/demos/titanium-date-input/titanium-date-input-playground.ts
packages/leavittbook/src/demos/titanium-date-range-selector/titanium-date-range-selector-playground.ts
packages/leavittbook/src/my-app.ts
packages/web/titanium/date-input/date-input.ts
packages/web/titanium/date-range-selector/date-range-selector.ts
packages/web/titanium/date-range-selector/types/date-ranges.ts
packages/web/titanium/date-range-selector/types/range-label.ts

fixes: [#541](https://github.com/LeavittSoftware/titanium-elements/issues/541)

feat: date-input and date-range-selector redesigned

---

packages/web/titanium/address-input/google-address-input.ts
packages/web/titanium/single-select-base/single-select-base.ts

569 Add powered-by google logo to address input

---

packages/web/titanium/icon-picker/icon-picker.ts

Closes #580
Search for a icon -> Search for an icon

fix(icon-picker): default placeholder text

---

packages/web/titanium/chip-multi-select/chip-multi-select.ts

584 chip-multi-select reset can throw if called too early because this.validator is null

---

packages/web/titanium/confirm-dialog/confirm-dialog.ts
packages/web/titanium/hacks/dialog-navigation-hack.ts

@aarondrabeck what do you think about this? Added it to the confirm dialog. Can be tested on the confirm dialog demo page.
closes #585

585 Dialogs: navigate when open doesn't close

---

packages/leavittbook/src/demos/titanium-icon-picker/titanium-icon-picker-playground.ts
packages/web/titanium/icon-picker/icon-picker.ts

589 Add preferredSymbols to icon picker (be careful pls don't break everything)

---

packages/leavittbook/src/demos/titanium-profile-picture-stack/index.html
packages/leavittbook/src/demos/titanium-profile-picture-stack/project.json
packages/leavittbook/src/demos/titanium-profile-picture-stack/titanium-profile-picture-stack-demo.ts
packages/leavittbook/src/demos/titanium-profile-picture-stack/titanium-profile-picture-stack-playground.ts
packages/leavittbook/src/my-app.ts
packages/web/titanium/profile-picture-stack/profile-picture-stack.ts

feat(titanium-profile-picture-stack): Adds profile picture stack element

---

packages/web/titanium/date-range-selector/types/range-label.ts

fix(date-range-selector): logic for from/to labels is backwards

---

packages/web/leavitt/company-select/company-select.ts
packages/web/leavitt/person-company-select/person-company-select.ts
packages/web/leavitt/person-group-select/person-group-select.ts
packages/web/leavitt/person-select/person-select.ts
packages/web/leavitt/user-manager/user-manager.ts
packages/web/titanium/address-input/google-address-input.ts
packages/web/titanium/data-table/page-control.ts
packages/web/titanium/duration-input/duration-input.ts
packages/web/titanium/extendable-outlined-text-field/extendable-outlined-text-field.ts
packages/web/titanium/icon-picker/icon-picker.ts
packages/web/titanium/search-input/search-input.ts
packages/web/titanium/single-select-base/single-select-base.ts
packages/web/titanium/youtube-input/youtube-input.ts

Addresses this issue: https://github.com/LeavittSoftware/reportingtools.leavitt.com/issues/274

feat(single-select-base): Add autocomplete

---

package.json
packages/leavittbook/src/my-app.ts
packages/web/leavitt/user-feedback/provide-feedback-dialog.ts
packages/web/leavitt/user-feedback/report-a-problem-dialog.ts
packages/web/leavitt/user-feedback/user-feedback.ts

feat(user-feedback): point to new controllers; adds url path for reports

---

packages/web/titanium/address-input/manual-address-dialog.ts

[Linked issue](https://github.com/LeavittSoftware/workforce.leavitt.com/issues/66#issue-2490455126)

fix(manual-address-dialog): add z-index hack

---

packages/leavittbook/src/demos/titanium-profile-picture-stack/titanium-profile-picture-stack-playground.ts
packages/web/titanium/profile-picture-stack/profile-picture-stack.ts

closes #619
I've realized that this is probably an element better suited to be in the leavitt element structure instead of titanium. I can move that at some point

619 Add a +N circle to profile picture stack

---

packages/leavittbook/src/demos/titanium-profile-picture-stack/titanium-profile-picture-stack-playground.ts
packages/web/titanium/profile-picture-stack/profile-picture-stack.ts

closes #623
Without ellipsis on the p tag I exposed a shadow part to allow styling so the user can choose to add ellipsis or reduce font size etc..

623 Update profile picture stack

---

packages/web/titanium/smart-attachment-input/smart-attachment-input.ts

croppableImageFormats now respects uppercase file

fix(smart-attachment-input): uppercase extension support

---

packages/leavittbook/src/demos/profile-picture/profile-picture-playground.ts
packages/web/leavitt/profile-picture/profile-picture.ts

feat(profile-picture): add test user indicator option

---

packages/leavittbook/src/demos/titanium-smart-attachment-input/titanium-smart-attachment-input-playground.ts
packages/web/titanium/smart-attachment-input/crop-and-save-image-dialog.ts

- Adds `constrainSelectionTo` to allow constraining selection to image or canvas
- Adds `maximizeSelection` to fit initial selection to image

Add cropper selection options

---

packages/leavittbook/src/demos/titanium-page-control/titanium-page-control-playground.ts
packages/web/titanium/data-table/page-control.ts

feat(page-control): adds filled support

---

packages/leavittbook/src/demos/titanium-smart-attachment-input/titanium-smart-attachment-input-playground.ts
packages/web/titanium/smart-attachment-input/crop-and-save-image-dialog.ts
packages/web/titanium/smart-attachment-input/smart-attachment-input.ts

closes #668
I think we maybe thought there was more to this but most of the work was in the multi-chip input

668 Add filled support to smart-attachment
