packages/titanium-card/src/titanium-card-list-item.ts
A border on both top and bottom matches the original design from google accounts page, and creates better borders around the items.
=> fix: Added border to top of card-list-item on hover

packages/storybook/stories/data-table.stories.js, packages/titanium-data-table/src/titanium-data-table-header.ts
The purpose of this PR is to make it so that when one switches between active table headers the sort direction does not change.  When the user changes the sort direction by clicking on an active table header it stays that way again between switches between headers.
=> fix: Improved UX of sorting with titanium data table header

packages/titanium-data-table/src/titanium-data-table.ts
BREAKING CHANGE: Data Table no longer emits an initial page change event when it is connected.
=> fix: Supresses intial page-chage event (0) on DT load

packages/titanium-loading-indicator/src/titanium-full-page-loading-indicator.ts
This change solves the issue of pages being scrolled to the top whenever a modal is opened for the first time.
Currently the way that full-page-loading-indicator is setting styles, on open and close, is causing modals to scroll the body of a page to the top. Some pages are very short, so it's not a huge issue on those, but others scroll quite a bit (The hire form on employee manager being the main example here).
I noticed that these styles were added in to fix a scroll issue about a month ago, but after effectively reverting those changes, I can't find what the scrolling issue was previously. 
The scrolling only happens when an api call is made, but the styling here seems to be affecting it as well. I haven't been able to track down an api-service or network related issue that's causing …
=> Loading scroll issue

packages/titanium-address-input/src/google-address-input.ts, packages/titanium-address-input/src/titanium-address-input.ts
Fixes:
- Focusing and exiting a non-required field causes error state.
- Field enters invalid state on first .reset() after loading.
- Request to google API was requesting all data fields back costing extra money and bandwidth.
=> Fix titanium-address-input going into error state when it's not supposed to.

packages/titanium-image-input/src/image-cropper-dialog.ts
- Image input was leaving a ghost image when uploading and then canceling in the cropper dialog.
- Uploading a large image would show the previously loaded image while uploading the new one. 
You can see the bug by going here:
https://devservicetimeline.leavitt.com/admin/cover-pages/add
https://devstationery.leavitt.com/business-cards/111/company/20248
=> Remove cropper image on close dialog

packages/titanium-side-menu/src/titanium-side-menu-item.ts
Before | After
:------:|:-----:
=> Remove line-height from titanium-side-menu-item so align-items: center can do its thing properly

packages/titanium-loading-indicator/src/titanium-full-page-loading-indicator.ts
Should fix issue where sometimes pages fully load but the veil doesn't go away.
https://devpcms.leavitt.com/sales-expectation/10934/expectations seems to trigger the issue often
=> fix(titanium-loading-indicator): ensure veil is closed when closing is done

packages/leavitt-elements/src/leavitt-company-select.ts, packages/leavitt-elements/src/leavitt-person-company-select.ts, packages/leavitt-elements/src/leavitt-person-group-select.ts, packages/leavitt-elements/src/leavitt-person-select.ts
BREAKING CHANGE: defaults position to relative vs fixed.  Use fixedMenuPosition if fixed is desired. 
closes #389
=> feat(leavitt-elements): expose fixedMenuPosition in elements with menu

packages/leavitt-elements/src/mwc-datefield.ts
=> 407 Date picker in the filters is allowing an input of six digits for the year.

packages/leavittbook/package.json, packages/leavittbook/src/demos/titanium-duration-input/index.html, packages/leavittbook/src/demos/titanium-duration-input/project.json, packages/leavittbook/src/demos/titanium-duration-input/titanium-duration-input-demo.ts, packages/leavittbook/src/demos/titanium-duration-input/titanium-duration-input-playground.ts, packages/leavittbook/src/my-app.ts, packages/titanium-duration-input/.gitignore, packages/titanium-duration-input/package.json, packages/titanium-duration-input/src/human-interval.ts, packages/titanium-duration-input/src/titanium-duration-input.ts, packages/titanium-duration-input/tsconfig.json, tsconfig.json
closes #411
Reworked the duration input to have a simpler API.
Input should just be duration in and duration out.
Replaced luxon with dayjs.
Extend textfield instead of encapsulate to reduce boilerplate
=> 411 Create a titanium-duration-input component (take it from logs.leavitt.com)

packages/leavittbook/src/demos/titanium-attachment-input/titanium-attachment-input-playground.ts, packages/titanium-attachment-input/src/titanium-attachment-input.ts
=> 413 titanium-attachment-input: "delete" icon doesn't look disabled when the rest of the component is disabled

packages/leavittbook/src/demos/titanium-dialog-base/titanium-dialog-base-playground.ts, packages/titanium-dialog/src/titanium-native-dialog-base.ts
Prevents scrim from getting stuck on top of all other pages
=> fix(titanium-dialog): close dialog when navigating away from page

packages/leavittbook/src/demos/titanium-dialog-base/titanium-dialog-base-playground.ts, packages/titanium-dialog/src/titanium-native-dialog-base.ts
Emit a reason for closed dialogs that are canceled (via esc key)
=> fix(titanium-dialog): prevent esc key from closing dialogs that are focus trapped

packages/leavittbook/src/demos/titanium-chip/titanium-chip-playground.ts, packages/titanium-chip/src/titanium-chip.ts
closes #417
**Before**
**After**
=> 417 Find a way to make chips with and without icons and images line up in a inline container

packages/leavitt-elements/package.json, packages/leavitt-elements/src/mwc-datefield.ts
closes #440 
This is a temporary fix until material 3 components arrive. Also removes old style code that isn't needed anymore
=> 440 In MWC Datefield check if safari and hide the icon to prevent the click autoclose of the date picker problem

packages/leavittbook/src/demos/titanium-date-range-selector/titanium-date-range-selector-playground.ts, packages/titanium-date-range-selector/src/date-range-change-event.ts, packages/titanium-date-range-selector/src/titanium-date-range-selector.ts
Adds ability to override range options on titanium-date-range-selector.
Couldn't figure out how to do it without relaxing type checking on TitaniumDateRangeSelector.range
=> feat(titanium-date-range-selector): allow custom range options

packages/titanium-helpers/src/titanium-search-token.ts
=> 449 searching with more than 3 tokens in the data table doesn't sanitize the search input ('&' will break odata)

packages/leavitt-file-explorer/src/leavitt-file-modal.ts
Installed version of dialog on Apps.leavitt.com did not pass in `--titanium-dialog-max-height`, with update the explicit height is causing modal to overflow window on laptop screens.
=> fix: remove explicit max height on file modal

packages/titanium-smart-attachment-input/src/titanium-smart-attachment-input.ts
=> 460 You can drop more than 1 image into a titanium-smart-attachment-input even if it has multiple=false

packages/titanium-smart-attachment-input/src/crop-and-save-image-dialog.ts
any expenses uploaded right now on expenses.leavitt.com from chrome on an iPhone is creating a broken image. We can't simply check the browser here so I changed it to be an OS check.
=> fix: check on OS instead of browser

packages/leavittbook/src/demos/titanium-show-hide/titanium-show-hide-playground.ts, packages/titanium-show-hide/src/titanium-show-hide.ts, packages/titanium-side-menu/src/titanium-side-menu-item.ts
allow for custom text, alignment, and button type
This will allow for the directory and recruiting sites to use titanium-show-hide instead of a local component.
Thank you for your consideration.
=> Allow for more button configuration

packages/api-service/src/api-service.ts
=> 474 Make Api Service alert on double //

packages/leavitt-elements/src/leavitt-person-company-select.ts, packages/leavitt-elements/src/leavitt-person-group-select.ts, packages/leavitt-elements/src/leavitt-person-select.ts, packages/leavittbook/src/demos/leavitt-person-company-select/leavitt-person-company-select-playground.ts, packages/leavittbook/src/demos/leavitt-person-select/leavitt-person-select-playground.ts, packages/leavittbook/src/demos/profile-picture/profile-picture-playground.ts, packages/leavittbook/src/demos/titanium-chip/titanium-chip-playground.ts, packages/profile-picture/src/profile-picture-menu-popup.ts, packages/profile-picture/src/profile-picture-menu.ts, packages/profile-picture/src/profile-picture.ts, packages/user-manager/src/LssJwtToken.ts, packages/user-manager/src/user-manager.ts
BREAKING CHANGE:  profile-picture personId property has been removed. Use fileName to supply profile picture file name off the CDN.  link-to-profile was replaced by profile-picture-link-person-id where a person id must be supplied to construct a valid link to directory.  All cache busting was removed because it is no longer needed with this approach.  A profilePictureFileName was added to user manager to supply picture file name of logged in user.
=> feat: change profile picture to drive off filename vs personId

packages/leavittbook/404.html, packages/leavittbook/index.html, packages/leavittbook/rollup.config.js
closes #516
SPA are NOT natively supported. This is a hack I want to try.
https://github.com/rafgraph/spa-github-pages
Here is the issue saying spa routing isn't supported by github pages. Their recommendations are to move to other free hosting services when a SPA is a requirement.
https://github.com/isaacs/github/issues/408
=> Use spa routing hack for github pages

packages/web/titanium/search-input/search-input.ts
clicking on the button in safari doesn't trigger a focus event. Probably an issue that should be elevated to md-components, but for now, this fixes the issue without any apparent side effects.
before
https://github.com/LeavittSoftware/apps.leavitt.com/assets/590826/a6a3dcf2-ff0a-40ad-8ac4-00f53fe91961
after
https://github.com/LeavittSoftware/apps.leavitt.com/assets/590826/8b6d6b6d-d6a5-4c0e-a702-9a06851f7525
=> fix(search-input): search-input not opening on click in safari

packages/web/titanium/youtube-input/youtube-input.ts
=> Fix thumbnail placement

packages/web/titanium/smart-attachment-input/smart-attachment-input.ts
Fixes typo in the shape type option for square by removing leading space.
=> fix(titanium-smart-attachment-input): Fix shape type typo
